# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MiProfeEnCasa' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AlamofireImage' 
  pod 'OAuthSwift'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SWRevealViewController'
  pod 'GBFloatingTextField'
  pod 'Segmentio', '~> 3.3'
  pod "PickerButton"
end
